# Generated by Django 5.2.8 on 2025-12-22 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0008_alter_tarif_in_archive'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application_from_user',
            fields=[
                ('id', models.CharField(editable=False, max_length=6, primary_key=True, serialize=False)),
                ('application_status', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('data_create', models.DateTimeField(auto_now=True, verbose_name='Когда создали заявку')),
                ('user', models.CharField(blank=True, max_length=50, null=True, verbose_name='Фио если нет модели')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Номер если нет модели')),
                ('adres', models.CharField(blank=True, max_length=100, null=True, verbose_name='Адрес без модели')),
                ('FromOrder', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Модель от кого пришел')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='Кому заказ принадлежит')),
                ('tariffield', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.tarif', verbose_name='Выбраный тариф')),
            ],
        ),
    ]
