# Generated by Django 5.2.8 on 2026-04-24 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application_from_user',
            fields=[
                ('id', models.CharField(editable=False, max_length=6, primary_key=True, serialize=False)),
                ('application_status', models.CharField(choices=[('opt1', 'Заявка заведена'), ('opt2', 'Неуспешно'), ('opt3', 'Новая заявка'), ('opt4', 'Доработка'), ('opt5', 'Юридическая заявка')], default='opt3', max_length=50)),
                ('comment', models.TextField(blank=True, null=True)),
                ('data_create', models.DateTimeField(auto_now=True, verbose_name='Когда создали заявку')),
                ('user', models.CharField(blank=True, max_length=50, null=True, verbose_name='Фио если нет модели')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Номер если нет модели')),
                ('adres', models.CharField(blank=True, max_length=100, null=True, verbose_name='Адрес без модели')),
                ('type_manager_take', models.CharField(choices=[('opt1', 'Техническая поддержка'), ('opt2', 'Монтажник'), ('opt3', 'Продажи')], default='opt3', max_length=60)),
            ],
        ),
    ]
