# Generated by Django 5.2.8 on 2026-05-13 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application_from_user',
            name='first_owner_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_applications', to=settings.AUTH_USER_MODEL, verbose_name='Кто первый взял заявку'),
        ),
        migrations.AlterField(
            model_name='application_from_user',
            name='FromOrder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Модель от кого пришел'),
        ),
        migrations.AlterField(
            model_name='application_from_user',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='Кому заказ принадлежит'),
        ),
        migrations.AlterField(
            model_name='application_from_user',
            name='tariffield',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.tarif', verbose_name='Выбраный тариф'),
        ),
    ]
