# Generated by Django 5.0.7 on 2025-12-21 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application_from_user',
            name='user',
        ),
    ]
