# Generated by Django 5.2.8 on 2026-05-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_application_from_user_first_owner_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application_from_user',
            name='type_manager_take',
            field=models.CharField(choices=[('opt1', 'Техническая поддержка'), ('opt2', 'Монтажник'), ('opt3', 'Продажи'), ('opt4', 'Менеджер')], default='opt3', max_length=60),
        ),
    ]
