# Generated by Django 5.0.7 on 2025-12-21 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_remove_application_from_user_user'),
        ('user', '0007_remove_usermodel_number_user_id_usermodel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='application_from_user',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usermodel'),
        ),
    ]
