# Generated by Django 5.2.8 on 2026-05-15 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_application_from_user_type_manager_take'),
    ]

    operations = [
        migrations.AddField(
            model_name='application_from_user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
