# Generated by Django 5.2.8 on 2026-05-15 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_application_from_user_is_active'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application_from_user',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.typeproblem'),
        ),
    ]
