# Generated by Django 5.0.7 on 2025-12-21 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_application_from_user_user'),
        ('user', '0013_usermodel_numberphone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application_from_user',
            name='FromOrder',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usermodel', verbose_name='Модель от кого пришел'),
        ),
        migrations.AddField(
            model_name='application_from_user',
            name='adres',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Адрес без модели'),
        ),
        migrations.AddField(
            model_name='application_from_user',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='user.usermodel', verbose_name='Кому заказ принадлежит'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application_from_user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Номер если нет модели'),
        ),
        migrations.AlterField(
            model_name='application_from_user',
            name='data_create',
            field=models.DateTimeField(auto_now=True, verbose_name='Когда создали заявку'),
        ),
        migrations.AlterField(
            model_name='application_from_user',
            name='id',
            field=models.CharField(editable=False, max_length=6, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='application_from_user',
            name='user',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Фио если нет модели'),
        ),
    ]
