# Generated by Django 5.0.7 on 2025-12-21 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_application_from_user_fromorder_and_more'),
        ('user', '0013_usermodel_numberphone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application_from_user',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='user.usermodel', verbose_name='Кому заказ принадлежит'),
        ),
    ]
