# Generated by Django 5.0.7 on 2025-12-21 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_alter_application_from_user_order'),
        ('main', '0006_tarif_tv_chanels'),
    ]

    operations = [
        migrations.AddField(
            model_name='application_from_user',
            name='tarif',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.tarif', verbose_name='Выбраный тариф'),
        ),
        migrations.AlterField(
            model_name='application_from_user',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
