# Generated by Django 5.0.7 on 2025-12-21 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_application_from_user_tarif_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application_from_user',
            old_name='tarif',
            new_name='tariffield',
        ),
    ]
