# Generated by Django 5.2.8 on 2026-05-25 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_alter_logs_who'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logs',
            old_name='who',
            new_name='user_who',
        ),
    ]
