# Generated by Django 5.2.8 on 2026-05-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_rename_who_logs_user_who'),
    ]

    operations = [
        migrations.AddField(
            model_name='application_from_user',
            name='color',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
