# Generated by Django 5.2.8 on 2026-05-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_application_from_user_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application_from_user',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
