# Generated by Django 5.2.8 on 2026-06-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_alter_application_from_user_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='application_from_user',
            name='response',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='application_from_user',
            name='application_status',
            field=models.CharField(choices=[('opt1', 'Заявка заведена'), ('opt2', 'Неуспешно'), ('opt3', 'Новая заявка'), ('opt4', 'Заявка обработана'), ('opt5', 'Юридическая заявка')], default='opt3', max_length=50),
        ),
    ]
