# Generated by Django 5.2.8 on 2026-04-24 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='typeproblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_problem', models.CharField(max_length=500)),
                ('difficulity', models.CharField(choices=[('opt1', 'Сложные тех. неполадки'), ('opt2', 'Средние тех. неполадки'), ('opt3', 'Легкие тех. неполадки')], default='opt1', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='TypeTarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typetarif', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='tarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tarif_name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('price_to_connect', models.IntegerField()),
                ('discounts', models.IntegerField(blank=True, null=True)),
                ('time_to_end_discount', models.DateField(blank=True, null=True)),
                ('Mounts_discount', models.IntegerField(blank=True, null=True)),
                ('in_archive', models.BooleanField(blank=True, default=False, null=True)),
                ('speed', models.IntegerField()),
                ('tv_chanels', models.IntegerField()),
                ('typetarif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.typetarif')),
            ],
        ),
    ]
