# Generated by Django 5.0.7 on 2025-12-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tarif_name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('price_to_connect', models.IntegerField()),
                ('discounts', models.IntegerField()),
                ('time_to_end_discount', models.DateField()),
                ('Mounts_discount', models.IntegerField()),
                ('in_archive', models.BooleanField()),
            ],
        ),
    ]
