# Generated by Django 5.2.8 on 2026-05-18 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarif',
            name='discounts_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
