# Generated by Django 5.0.7 on 2025-12-20 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarif',
            name='Mounts_discount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tarif',
            name='discounts',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tarif',
            name='in_archive',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='tarif',
            name='time_to_end_discount',
            field=models.DateField(null=True),
        ),
    ]
