# Generated by Django 5.0.7 on 2025-12-20 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_tarif_mounts_discount_alter_tarif_discounts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarif',
            name='speed',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarif',
            name='typetarif',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
