# Generated by Django 5.0.7 on 2025-12-20 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_tarif_speed_tarif_typetarif'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarif',
            old_name='typetarif',
            new_name='typetarif_for_code',
        ),
    ]
