# Generated by Django 5.0.7 on 2025-12-20 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_typetarif_tarif_typetarif_for_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeTarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typetarif', models.CharField(max_length=80)),
            ],
        ),
        migrations.RemoveField(
            model_name='tarif',
            name='typetarif_for_code',
        ),
        migrations.AddField(
            model_name='tarif',
            name='typetarif',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.typetarif'),
            preserve_default=False,
        ),
    ]
