# Generated by Django 5.0.7 on 2025-12-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_typetarif_remove_tarif_typetarif_for_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarif',
            name='tv_chanels',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
