# Generated by Django 5.0.7 on 2025-12-21 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_tarif_tv_chanels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarif',
            name='Mounts_discount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarif',
            name='discounts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarif',
            name='in_archive',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarif',
            name='time_to_end_discount',
            field=models.DateField(blank=True, null=True),
        ),
    ]
