# Generated by Django 5.0.7 on 2025-12-21 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_tarif_mounts_discount_alter_tarif_discounts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarif',
            name='in_archive',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
