# Generated by Django 5.0.7 on 2025-12-20 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settings', models.CharField(max_length=70)),
                ('cout_applications', models.IntegerField()),
                ('cout_applications_in_work', models.IntegerField()),
                ('in_work', models.BooleanField()),
                ('start_of_shift', models.DateTimeField()),
                ('end_of_shift', models.DateTimeField()),
                ('works_day', models.IntegerField()),
                ('work_hours', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('UserRole', models.IntegerField()),
                ('number_user_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('user_last_name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=300)),
                ('paper_data', models.CharField(max_length=10)),
                ('user_access', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.worker')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
