# Generated by Django 5.2.8 on 2026-04-24 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id_userlog', models.CharField(max_length=12, unique=True, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='Логин')),
                ('settings', models.CharField(blank=True, max_length=70, null=True, verbose_name='Настройки')),
                ('user_last_name', models.CharField(max_length=150, verbose_name='ФИО')),
                ('address', models.CharField(max_length=300, verbose_name='Адрес подключения')),
                ('paper_data', models.CharField(max_length=10, verbose_name='Паспортные данные')),
                ('cout_applications', models.IntegerField(blank=True, null=True, verbose_name='Все выполненые заявки')),
                ('cout_applications_in_work', models.IntegerField(blank=True, null=True, verbose_name='Все заявки в работе')),
                ('in_work', models.BooleanField(blank=True, default=False, null=True, verbose_name='Состояние смены')),
                ('start_of_shift', models.DateTimeField(blank=True, null=True, verbose_name='Начало смены')),
                ('end_of_shift', models.DateTimeField(blank=True, null=True)),
                ('works_day', models.IntegerField(blank=True, null=True)),
                ('work_hours', models.IntegerField(blank=True, null=True)),
                ('user_acces', models.IntegerField(blank=True, default=0, null=True)),
                ('userhash', models.CharField(max_length=128, unique=True)),
                ('numberphone', models.CharField(max_length=13)),
                ('balance', models.IntegerField(default=0)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('user_tarif', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.tarif')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
