# Generated by Django 5.2.8 on 2026-05-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='Date_of_last_write_off',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='Date_of_new_write_off',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user_last_name',
            field=models.CharField(max_length=150, null=True, verbose_name='ФИО'),
        ),
    ]
