# Generated by Django 5.0.7 on 2025-12-20 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='user_access',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='cout_applications',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='cout_applications_in_work',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='end_of_shift',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='in_work',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='settings',
            field=models.CharField(default=1, max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermodel',
            name='start_of_shift',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='user_acces',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='work_hours',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='works_day',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Worker',
        ),
    ]
