# Generated by Django 5.2.8 on 2025-12-22 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_tarif_in_archive'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='user_tarif',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.tarif'),
        ),
    ]
