# Generated by Django 5.0.7 on 2025-12-21 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_usermodel_user_access_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='cout_applications',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='cout_applications_in_work',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='in_work',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='work_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='works_day',
            field=models.IntegerField(default=0),
        ),
    ]
