# Generated by Django 5.2.8 on 2026-05-15 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('user', '0002_usermodel_date_of_last_write_off_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='user_tarif_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='user_tarif_balance',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user_tarif',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.tarif'),
        ),
    ]
