# Generated by Django 5.0.7 on 2025-12-21 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_usermodel_cout_applications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='UserName',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermodel',
            name='userhash',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
