# Generated by Django 5.2.8 on 2025-12-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_usermodel_user_tarif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='settings',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Настройки'),
        ),
    ]
