# Generated by Django 5.2.8 on 2026-05-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_usermodel_user_tarif_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='appartaments',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
