# Generated by Django 5.2.8 on 2026-05-20 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_usermodel_appartaments'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('Tech_inf', models.CharField(choices=[('opt1', 'Приложение было временно отключено, завдите через некоторое время!'), ('opt2', 'Сейчас ведутся технические работы ,подождите пожалуйста, для связи с нами позвоните по номеру "8(916)000 43-00"'), ('opt3', 'Обновление услуг, подождите некоторое время')], max_length=450)),
                ('time_to_end', models.DateTimeField()),
            ],
        ),
    ]
