# Generated by Django 5.0.7 on 2025-12-23 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_usermodel_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='user_acces',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
