# Generated by Django 5.0.7 on 2025-12-21 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_usermodel_username_usermodel_userhash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='number_user_id',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
