# Generated by Django 5.0.7 on 2025-12-23 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_usermodel_user_acces'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='in_work',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Состояние смены'),
        ),
    ]
