# Generated by Django 5.2.8 on 2026-05-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_serverstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverstatus',
            name='for_who',
            field=models.CharField(blank=True, choices=[('opt1', 'Users'), ('opt2', 'Emps')], max_length=10, null=True),
        ),
    ]
