# Generated by Django 5.2.8 on 2026-05-20 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_serverstatus_for_who'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverstatus',
            name='Tech_inf',
            field=models.CharField(choices=[('opt1', 'Приложение было временно отключено, зайдите через некоторое время!'), ('opt2', 'Сейчас ведутся технические работы ,подождите пожалуйста, для связи с нами позвоните по номеру "8(916)000 43-00"'), ('opt3', 'Обновление услуг, подождите некоторое время')], max_length=450),
        ),
        migrations.AlterField(
            model_name='serverstatus',
            name='for_who',
            field=models.CharField(blank=True, choices=[('User', 'Пользователи'), ('Emps', 'Сотрудники')], max_length=10, null=True, unique=True),
        ),
    ]
