# Generated by Django 5.2.8 on 2026-05-20 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_serverstatus_tech_inf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverstatus',
            name='time_to_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
