# Generated by Django 5.0.7 on 2025-12-21 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_usermodel_number_user_id_usermodel_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='UserRole',
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='userhash',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
