# Generated by Django 5.2.8 on 2026-06-21 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_serverstatus_time_to_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='userhash',
            field=models.CharField(max_length=128),
        ),
    ]
