# Generated by Django 5.0.7 on 2025-12-21 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_usermodel_userrole_alter_usermodel_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='UserName',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='username',
            field=models.CharField(default=1, max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
