# Generated by Django 5.2.8 on 2026-06-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_usermodel_userhash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
