# Generated by Django 5.0.7 on 2025-12-21 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_remove_usermodel_username_usermodel_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='username',
        ),
    ]
