# Generated by Django 5.2.8 on 2026-06-22 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_usermodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverstatus',
            name='for_who',
            field=models.CharField(blank=True, choices=[('User', 'Пользователи'), ('Emps', 'Сотрудники')], max_length=10, null=True),
        ),
    ]
