# Generated by Django 5.0.7 on 2025-12-21 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_usermodel_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='address',
            field=models.CharField(max_length=300, verbose_name='Адрес подключения'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='cout_applications',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='cout_applications_in_work',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='end_of_shift',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Айди'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='in_work',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='paper_data',
            field=models.CharField(max_length=10, verbose_name='Паспортные данные'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='settings',
            field=models.CharField(max_length=70, verbose_name='Настройки'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='start_of_shift',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user_acces',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user_last_name',
            field=models.CharField(max_length=150, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='username',
            field=models.CharField(max_length=150, unique=True, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='work_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='works_day',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
