# Generated by Django 5.0.7 on 2025-12-21 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_usermodel_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='numberphone',
            field=models.CharField(default=1, max_length=13),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='cout_applications',
            field=models.IntegerField(blank=True, null=True, verbose_name='Все выполненые заявки'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='cout_applications_in_work',
            field=models.IntegerField(blank=True, null=True, verbose_name='Все заявки в работе'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='in_work',
            field=models.BooleanField(blank=True, null=True, verbose_name='Состояние смены'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='start_of_shift',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начало смены'),
        ),
    ]
