# Generated by Django 5.0.7 on 2025-12-22 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_usermodel_numberphone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='id',
            field=models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='Айди'),
        ),
    ]
