# Generated by Django 5.0.7 on 2025-12-22 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_usermodel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
