# Generated by Django 5.0.7 on 2025-12-22 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_tarif_in_archive'),
        ('user', '0015_usermodel_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='user_tarif',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.tarif'),
            preserve_default=False,
        ),
    ]
